version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: pharmadash_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pharmadash
      POSTGRES_PASSWORD: pharmadash_pass
      POSTGRES_DB: pharmadash_db
    ports:
      - '5432:5432'
    volumes:
      - pharmadash_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pharmadash -d pharmadash_db']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pharmadash_pgdata:
