module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  setupFiles: ['<rootDir>/test/setup-env.ts'],
  roots: ['<rootDir>/src'],
  testMatch: ['**/*.spec.ts'],
  collectCoverageFrom: [
    'src/app.ts',
    'src/config/env.ts',
    'src/config/logger.ts',
    'src/config/database.ts',
    'src/modules/**/service.ts',
    'src/modules/**/repository.ts',
    'src/modules/**/controller.ts',
    'src/modules/**/schema.ts',
    'src/modules/**/routes.ts',
    'src/middlewares/validate.ts',
    'src/middlewares/error-handler.ts',
    'src/middlewares/correlation-id.ts',
    'src/shared/**/*.ts',
    '!src/shared/types/**',
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 75,
      functions: 80,
      lines: 80,
    },
  },
  coverageReporters: ['text', 'lcov', 'clover'],
  clearMocks: true,
};
